### ISSUE TITLE
Veritrans Error (404): Transaction doesn't exist.

### ISSUE THREAD

**Issue by PandhuWibowo** [veritrans/veritrans-php#101]
Saya sudah cari2 dan bertanya2 di beberapa tempat komunitas, dan sudah mengikuti semua instruksi di github issue midtrans juga #73 dan Exception: Veritrans Error (404): The requested resource is not found in #2 tapi tetap mengalami error yang sama, saya juga sudah mengikuti saran dari mas nurasto@15fbdf3 sampai edit package midtransnya, tetap saja tidak terjadi apa2. mohon bantuannya. terima kasih.

**Comment by rizdaprasetya** [comment]
Hi @PandhuWibowo silahkan dijelaskan detail issuenya. dapat 404 ini ketika call function/API tertentu kah?

Atau ketika dapat notifikasi, dan handle menggunakan function notif?

Ada sample URL yg dipakai sebagai penerima HTTP notification?

**Comment by rizdaprasetya** [comment]
Closed due to inactivity, if issue persist please reply.
