### ISSUE TITLE
wrong path, make sure it's `/charge`

### ISSUE THREAD

**Issue by masmul** [veritrans/veritrans-php#103]
Hi Selamat Malam,

Sya ingin mengimplementasi ke android dan mendapatkan masalah berikut

1.  saya sudah impementasi charge di sisi server (https://github.com/rizdaprasetya/midtrans-mobile-merchant-server--php-sample-)
  -folder berupa charge --> index.php
2. saya setting MERCHANT_BASE_CHECKOUT_URL =  https://serversaya.com/

ketika saya run mendapatkan Log berikut

05-08 01:24:52.591 24396-24396/com.tingtong.android I/MidtransSDK: Found 1 user addresses.
05-08 01:24:52.625 24396-24569/com.tingtong.android D/OkHttp: --> POST https://serversaya.com/charge
05-08 01:24:52.625 24396-24569/com.tingtong.android D/OkHttp: Content-Type: application/json
05-08 01:24:52.625 24396-24569/com.tingtong.android D/OkHttp: Content-Length: 637
05-08 01:24:52.625 24396-24569/com.tingtong.android D/OkHttp: Accept: application/json
05-08 01:24:52.626 24396-24569/com.tingtong.android D/OkHttp: {"customer_details":{"billing_address":{"address":"uvuvuv","city":"vyuv","country_code":"IDN","first_name":"uvuv","phone":"0606338","postal_code":"85086"},"email":"ugu@hmsil.com","first_name":"uvuv","phone":"0606338","shipping_address":{"address":"uvuvuv","city":"vyuv","country_code":"IDN","first_name":"uvuv","phone":"0606338","postal_code":"85086"}},"credit_card":{"authentication":"3ds","bank":"bca","save_card":false,"secure":true},"item_details":[{"id":"1","name":"Trekking Shoes","price":20000,"quantity":1}],"transaction_details":{"gross_amount":20000,"order_id":"1588875892331"},"user_id":"cfe21a33-dc97-41db-8b1b-2af90707a560"}
05-08 01:24:52.626 24396-24569/com.tingtong.android D/OkHttp: --> END POST (637-byte body)
05-08 01:24:52.754 24396-24540/com.tingtong.android D/OpenGLRenderer: endAllStagingAnimators on 0x55c0097ba0 (RippleDrawable) with handle 0x55c079ad10
05-08 01:24:52.971 24396-24569/com.tingtong.android D/OkHttp: <-- 404 https://serversaya.com/charge/ (344ms)
05-08 01:24:52.971 24396-24569/com.tingtong.android D/OkHttp: date: Thu, 07 May 2020 18:24:52 GMT
05-08 01:24:52.971 24396-24569/com.tingtong.android D/OkHttp: content-type: text/html; charset=UTF-8
05-08 01:24:52.971 24396-24569/com.tingtong.android D/OkHttp: vary: Accept-Encoding
05-08 01:24:52.972 24396-24569/com.tingtong.android D/OkHttp: wrong path, make sure it's `/charge`
05-08 01:24:52.972 24396-24569/com.tingtong.android D/OkHttp: <-- END HTTP (36-byte body)

kenapa 404 not found ya?

**Comment by masmul** [comment]
jika saya ganti basenya ditambah index.php android akan force close

Caused by: java.lang.IllegalArgumentException: baseUrl must end in /: https://serversaya.com/charge/index.php

**Comment by rizdaprasetya** [comment]
> kenapa 404 not found ya?

Silahkan dicek config servernya, kemungkinan config tidak standar, karena yg route `/charge/` ke `/charge/index.php` adalah servernya.

Bisa silahkan coba input
`https://serversaya.com/charge/index.php/`
atau
`https://serversaya.com/charge/index.php?/`
