### ISSUE TITLE
Opsi pembayaran dengan currency dollar

### ISSUE THREAD

**Issue by mfakhrys** [veritrans/veritrans-php#104]
Apakah ada pengaturan untuk menerima pembayaran dalam currency dollar?

**Comment by rizdaprasetya** [comment]
Hi @mfakhrys mengikuti regulasi Bank Indonesia, currency pembayaran yang diterima adalah dalam IDR. Silahkan lakukan konversi di sisi system Anda sebelum melakukan call ke API Midtrans. Jadi misalnya Anda masih bisa menampilkan total payment dalam currency USD di UI web/app Anda, untuk ditagihkan ke sisi customer, kemudian secara data yang dikirim ke API Midtrans adalah yang sudah dikonversi ke IDR.

**Comment by rizdaprasetya** [comment]
Untuk mendapat jawaban yang lebih cepat untuk pertanyaan seputar Midtrans silahkan tanyakan via email `support[at]midtrans.com`

**Comment by Chandrakus** [comment]
Mas saya ingin bertanya, cara menerima pembayaran selain rupiah di midtrans itu gimana yaa misal dollars ? Saya baca² di website midtrans "Anda dapat menjual produk menggunakan mata uang asing, namun Anda harus melakukan konversi ke Rupiah sebelum mengirimkan payment/charge request ke sistem Midtrans. Mengikuti regulasi Bank Indonesia, Midtrans hanya memproses transaksi dalam Rupiah." Saya masih kurang paham. Berarti nanti pembeli saya bayar menggunakan rupiah atau gimana ? Terima kasih sebelumnya

**Comment by Andrenzo17** [comment]
HI @Chandrakus 

Untuk pembeli membayar tetap menggunakan mata uang Rupiah. Semisal harga barangnya 1 USD, berarti charge request yang dikirim ke Midtrans bukan 1 USD akan tetapi Rp 14.400 IDR. Dimana jumlah tersebut dari total konversi bukan dalam bentuk USD-nya.

untuk penyelesaian yang lebih personal & menjaga keamanan/privasi akun Anda, kami sarankan untuk melanjutkan menghubungi kami secara direct message melalui jalur kontak berikut: https://midtrans.com/id/contact-us/technical-integration-development/other-question

Terima kasih

**Comment by Chandrakus** [comment]
Berarti setelah saya charge request ke midtrans pembeli saya transfernya
menggunakan rupiah kak? Atau tetap pakai dollar saya yg meneruskan charge
request menggunakan rupiah ke midtrans?

Terima kasih

Pada tanggal Sen, 6 Jun 2022 14.41, Andre S ***@***.***>
menulis:

**Comment by Andrenzo17** [comment]
Hi @Chandrakus untuk pembayaran baik melalui transfer VA, credit card ataupun metode pembayaran lain yang di proses melalui Midtrans tetap harus menggunakan IDR Rupiah ya.

Terima kasih

**Comment by Chandrakus** [comment]
Iya mas berarti pembeli saya nanti bayar pakai rupiah saat transfer dari
kartu kreditnya  ?

Pada tanggal Sen, 6 Jun 2022 18.18, Andre S ***@***.***>
menulis:

**Comment by Andrenzo17** [comment]
Benar, nantinya pada halaman 3DS/OTP kartu kredit milik user tetap dalam mata uang Rupiah.

**Comment by Andrenzo17** [comment]
Hi mas @Chandrakus 

maaf merevisi jawaban saya sebelumnya. Umumnya buat pembayaran kartu kredit, dari sisi Visa/Mastercard support pembayaran dari currency berbeda antara penerbit kartu & acquirer (penerbit kartu bisa dalam USD, merchantnya bisa dalam IDR). 

Jadi tidak ada masalah jika pembeli menggunakan kartu USD dan dari merchant melakukan charge menggunakan IDR.
Terima kasih

**Comment by Chandrakus** [comment]
Jadi pembeli saya tetap menggunakan dollar saat pembayaran mas ?

Pada tanggal Jum, 10 Jun 2022 15.18, Andre S ***@***.***>
menulis:

**Comment by Andrenzo17** [comment]
Hi mas @Chandrakus 

Saya tidak bisa memastikan apakah yang tampil pada halaman OTP/3DS dari kartu kredit milik customer dalam bentuk USD atau IDR. Saya hanya clarify walaupun di sisi Merchant melakukan proses charge dengan IDR, customer tetap bisa melakukan pembayaran menggunakan kartu kredit USD.

Terima kasih

**Comment by Chandrakus** [comment]
Sore mas ada yang ingin saya tanyakan kembali, saat transaksi pembayaran
dari pembeli ke toko saya melalui midtrans. Apa midtrans menahan dana saya
dulu sebelum pesanan pembeli saya sampai ke rumahnya terlebih dahulu atau
tidak ?

Terima kasih

Pada tanggal Jum, 10 Jun 2022 18.32, Andre S ***@***.***>
menulis:

**Comment by rizdaprasetya** [comment]
hi @Chandrakus Midtrans adalah Payment Gateway dan bukan platform Escrow/Ecommerce, jadi dana tidak ditahan berdasarkan pesanan sampai atau tidak. Tetapi perlu di perhatikan ada waktu (settlement) yang diperlukan sebelum dana bisa ditarik. Silahkan refer ke artikel berikut untuk lebih lengkapnya:
https://support.midtrans.com/hc/id/articles/204382884-Bagaimana-cara-mencairkan-dana-Saya-
