### ISSUE TITLE
Trying to access array offset in value of type null , transaction_idnya valid

### ISSUE THREAD

**Issue by alhamdibahri** [veritrans/veritrans-php#106]
![1629995255157](https://user-images.githubusercontent.com/27905103/131000344-82095ccf-f098-4f04-8ea2-be57e645c7d9.jpg)

**Comment by Andrenzo17** [comment]
Hi @alhamdibahri could you more clarify about this issue and share detail error log.
Thank you

**Comment by alhamdibahri** [comment]
@Andrenzo17 problem solved, on my server using laravel octane which causes the error like the picture. and i tried to use without laravel octane , and it worked fine
