### ISSUE TITLE
ErrorException: array_key_exists(): Using array_key_exists() on objects is deprecated.

### ISSUE THREAD

**Issue by stuckkode** [veritrans/veritrans-php#107]
ErrorException: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in file /var/www/user/vendor/veritrans/veritrans-php/Veritrans/Notification.php on line 26

**Comment by rizdaprasetya** [comment]
Hi all, as [announced on the readme file](https://github.com/veritrans/veritrans-php#:~:text=Please%20use%20the%20updated%20and%20composer%20compatible%20library%3A%20Midtrans%20PHP.%20For%20better%20more%20modern%20composer%20compatibility.) please use and update to use https://github.com/Midtrans/midtrans-php instead. Thanks
