### ISSUE TITLE
My two cents for veritrans

### ISSUE THREAD

**Issue by niteshpawar** [veritrans/veritrans-php#16]
Hello,

  I developed Commerce Veritrans Module(https://www.drupal.org/project/commerce_veritrans) for drupal. At the time of development I found there is minor bug in Veritrans-php. So I resolved it and sent you pull request for it( https://github.com/veritrans/veritrans-php/pull/13 ).
   It will be great if you add client key also in config.php, right now I am fetching it directly from database and assigning it to tokens(https://github.com/veritrans/veritrans-php/pull/12). 
    Another thing I need to specify version number for veritrans-php library or veritrans(2.0). Right now I am fetching it from README.md line no. 6. But its will be nice if you add this library version or veritrans version in composer.json(https://github.com/veritrans/veritrans-php/pull/14).

Thanks in advance.

**Comment by rafeequl** [comment]
Hi Nitesh,

For versioning we're using tag and packagist, so it will be on tag / release.
As for the rest, I'm assigning my college @andrisetiawan  to review your PR. Thank you for inputs ! 

Regards!

**Comment by niteshpawar** [comment]
Hi rafeequl,
 
Thanks for your reply,
For git repository its good that you are using tag/ releses but i see a difficulty here. Consider a case where an existing website is using this library which was downloaded as a zip rather than cloning the repository, here how will a user find the version of this php library.I just saw a paymet processor which specifies its version as follows: https://github.com/iATSPayments/PHP/blob/master/composer.json
Appreciate any help,

**Comment by niteshpawar** [comment]
Hello rafeequl,

Any updates on ( https://github.com/veritrans/veritrans-php/pull/13 ) and (https://github.com/veritrans/veritrans-php/pull/12) ?

Regards!
