### ISSUE TITLE
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by adisoe** [veritrans/veritrans-php#18]
Dear,

ada yang pernah mengalami ini?
localhost apache server menggunakan windows
sudah dicoba mengganti cacert.pem tapi masalahnya sama

[User Error] Uncaught Exception: CURL Error: SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Thx.

**Comment by Paxa** [comment]
What version of php you using?
Are you making request to https://api.veritrans.co.id or https://api.sandbox.veritrans.co.id?

Temporary you can add:
```php
# Veritrans/ApiRequestor.php
# before $result = curl_exec($ch);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
```

I try with php 5.4 and command line curl, both working fine, can not reproduce your problem. Certificates looks ok for me.

Also we disable sslv3 on our servers after security problems announces. May be this will help:

```php
# Veritrans/ApiRequestor.php
# before $result = curl_exec($ch);
curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_0);
```

**Comment by adisoe** [comment]
Dear,

I use sandbox for request, PHP Version 5.3.14

try:
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
error:
Veritrans Error (413): The request cannot be processed due to malformed syntax in the request body

try:
curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_0);
error:
Use of undefined constant CURL_SSLVERSION_TLSv1_0 - assumed 'CURL_SSLVERSION_TLSv1_0'

am i need to change my php version to 5.4? 
but some of our client hosting still user php 5.3 :)
thx for fast response

**Comment by Paxa** [comment]
Right, in php5.3 that constants are not defined. Let's try this:

```php
# Veritrans/ApiRequestor.php
# in top

if (!defined('CURL_SSLVERSION_TLSv1')) {
  define('CURL_SSLVERSION_TLSv1', 1);
}

if (!defined('CURL_SSLVERSION_SSLv2')) {
  define('CURL_SSLVERSION_SSLv2', 2);
}

if (!defined('CURL_SSLVERSION_SSLv3')) {
  define('CURL_SSLVERSION_SSLv3', 3);
}
```

And set extra options:
```php
# Veritrans/ApiRequestor.php
# before $result = curl_exec($ch);
curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1);
curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
```

Probably it's same problem with that one: https://github.com/paypal/adaptiveaccounts-sdk-php/releases/tag/v3.8.107

Can you try please to disable certificate file so we can be see if problem with certificate or curl options:

```php
# Disable this:
curl_setopt ($ch, CURLOPT_CAINFO, dirname(__FILE__) . "/../data/cacert.pem");
```

----

> try:
> curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
> error:
> Veritrans Error (413): The request cannot be processed due to malformed syntax in the request body

As I see `Veritrans Error` means that request complete but there is a problem with processing your request by our server. Probably you don't send any data, I can tell more if I can see your request params

**Comment by adisoe** [comment]
Dear,

my latest curl option settings (before curl_exec):
//curl_setopt ($ch, CURLOPT_CAINFO, dirname(__FILE__) . "/../data/cacert.pem");
//curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1);
curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

error:
Uncaught Exception: CURL Error: SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

try:
curl_setopt ($ch, CURLOPT_CAINFO, dirname(__FILE__) . "/../data/cacert.pem");
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1);
curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

error:
curl_setopt ($ch, CURLOPT_CAINFO, dirname(__FILE__) . "/../data/cacert.pem");
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1);
curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

#### dump of $transaction array:
array(4) {
  ["payment_type"]=>
  string(5) "vtweb"
  ["vtweb"]=>
  array(4) {
    ["credit_card_3d_secure"]=>
    bool(true)
    ["finish_redirect_url"]=>
    string(22) "http://www.example.com"
    ["unfinish_redirect_url"]=>
    string(22) "http://www.example.com"
    ["error_redirect_url"]=>
    string(22) "http://www.example.com"
  }
  ["transaction_details"]=>
  array(2) {
    ["order_id"]=>
    string(14) "INV20150200002"
    ["gross_amount"]=>
    float(78000)
  }
  ["customer_details"]=>
  array(6) {
    ["first_name"]=>
    string(3) "adi"
    ["last_name"]=>
    string(0) ""
    ["email"]=>
    string(18) "adixxxxx@yahoo.com"
    ["phone"]=>
    string(12) "0818xxxxxxxx"
    ["billing_address"]=>
    string(21) "xxxxxxxx"
    ["shipping_address"]=>
    string(21) "xxxxxxxx"
  }
}

**Comment by adisoe** [comment]
Finally found the problem..
The problem is because i call wrong value billing_address & shipping_address in $customer_details variable.
Doc can be found here (http://docs.veritrans.co.id/sandbox/charge.html#specification)
```
// Optional
    $billing_address = array(
        'first_name'    => $this->BillingName,
        'last_name'     => "",
        'address'       => $this->BillingAddress,
        'city'          => $this->BillingCity,
        'postal_code'   => $this->BillingZipCode,
        'phone'         => $this->BillingPhone,
        'country_code'  => 'IDN'
    );
    
    // Optional
    $customer_details = array(
        'first_name'    => $this->BillingName,
        'last_name'     => "",
        'email'         => $this->BillingEmail,
        'phone'         => $this->BillingPhone,
        'billing_address'  => $billing_address,  // PROBLEM HERE
        //'shipping_address' => $shipping_address  // PROBLEM HERE
    );
    
    // Fill transaction data
    $transaction = array(
        'payment_type' => 'vtweb',
        "vtweb" => array(
            "credit_card_3d_secure" => true,
            'finish_redirect_url' => 'http://www.example.com',
            'unfinish_redirect_url' => 'http://www.example.com',
            'error_redirect_url' => 'http://www.example.com'
        ),
        'transaction_details' => $transaction_details,
        'customer_details' => $customer_details,  // PROBLEM HERE
    );
```

Thx for support.
Hope help others too..

**Comment by Paxa** [comment]
Thank you for your report.

SSL verification still not working? Ok

I think we should add validation for that params

**Comment by adisoe** [comment]
if i try like this
```
curl_setopt ($ch, CURLOPT_CAINFO, dirname(__FILE__) . "/../data/cacert.pem");
    //curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1);
    curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
```

still not working and show error:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by Paxa** [comment]
We will try to solve it later

**Comment by adisoe** [comment]
ok thx :)
