### ISSUE TITLE
wrong Class Name on vt-web example file

### ISSUE THREAD

**Issue by arisdwisuryono** [veritrans/veritrans-php#25]
Using your example with veritrans-php/examples/vt-web/checkout-process.php 
my script get error with message Class Not Found.

found the error, turns out, the class name is not Veritrans_Vtweb. the correct one should be Veritrans_VtWeb. simple typo but give me a month of headache.

so i propose a fix on veritrans-php/examples/vt-web/checkout-process.php line 35
  header('Location: ' . Veritrans_Vtweb::getRedirectionUrl($params));
change to 
  header('Location: ' . Veritrans_VtWeb::getRedirectionUrl($params));

so no one would experience the same situation like i did.

Thank you

**Comment by yocki-s** [comment]
Hi Aris, 

Thanks for your information, we will check this.
