### ISSUE TITLE
Expire API implementation

### ISSUE THREAD

**Issue by robeth** [veritrans/veritrans-php#29]
Based on [docs](http://docs.veritrans.co.id/en/api/methods.html#Expire), now Veritrans has expire API.
By using this API, we can prevent transaction to be paid by customer.

Should we implement this in `veritrans-php`?

Changes would be minimum iif we add `expire` function in `Veritrans_Transaction.php` :smile:

**Comment by yocki-s** [comment]
yes robeth, we should add this.
