### ISSUE TITLE
SHA 512 validation when handling notification 

### ISSUE THREAD

**Issue by robeth** [veritrans/veritrans-php#30]
Based on [docs](http://docs.veritrans.co.id/en/api/methods.html#Validation), Veritrans provide addtional field named `signature_key` in notification JSON content.

`signature_key` is a proof that Veritrans is the sender of this notification. As `signature_key` use `server_key` in its calculation, only merchant and veritrans could validate this field.

PHP code that show how `signature_key` is calculated:

``` php
$order_id = "1111";
$status_code = "200";
$gross_amount = "100000";
$server_key = "askvnoibnosifnboseofinbofinfgbiufglnbfg";
$input = $order_id.$status_code.$gross_amount.$server_key;
$signature_key = openssl_digest($input, 'sha512');
```

Should we add this in `Veritrans_Notifications.php`? We'll only `get_status` if `signature_key` notifications is *verified*. 

Benefit: 
1. Additional _security layer_
2. Prevent merchant to do `get_status` if their notification end point is hit by attacker

Drawback:
1. More development :sweat: 
2. Computation overhead when merchant's server receive notification content

**Comment by yocki-s** [comment]
we use challenge status methods on  this library
