### ISSUE TITLE
Some minor variable error in Vt-Web sample code

### ISSUE THREAD

**Issue by rizdaprasetya** [veritrans/veritrans-php#33]
In PHP 5, this following code :
``$_SERVER[REQUEST_URI]`` found in **\examples\vt-web\index.php**
will produce this error :
``Notice: Use of undefined constant REQUEST_URI - assumed 'REQUEST_URI' ``

Explanation:
- since PHP 5, ``REQUEST_URI`` (without quotation mark) would be considered as **constant variable**, when it's not defined, above error notice would occur.
- Previously in PHP 4 and lower, ``REQUEST URI`` would be automatically converted into ``'REQUEST_URI'`` string (with quotation mark), no error notice would occur.

Fix suggestion:
- Simply change ``$_SERVER[REQUEST_URI]`` to ``$_SERVER['REQUEST_URI']``

**Comment by robeth** [comment]
Hi @rizdaprasetya, nice catch :+1: 

Could you make a pull request with for that? The other will review the code and merge it to our code base

**Comment by rizdaprasetya** [comment]
Done, [Pull request] (https://github.com/veritrans/veritrans-php/pull/34) created :+1:
