### ISSUE TITLE
Error result data from veritans

### ISSUE THREAD

**Issue by rachman123** [veritrans/veritrans-php#40]
Hello,

I want to test integrate veritrans with our website, but, while the transaction post to my site, error with this result below

Fatal error: Uncaught exception 'Exception' with message 'Veritrans Error (): ' in /home/roomnrate/public_html/veritrans/Veritrans/ApiRequestor.php:96 Stack trace: #0 /home/roomnrate/public_html/veritrans/Veritrans/ApiRequestor.php(17): Veritrans_ApiRequestor::remoteCall('https://api.san...', 'VT-server-kAuXE...', false, false) #1 /home/roomnrate/public_html/veritrans/Veritrans/Transaction.php(17): Veritrans_ApiRequestor::get('https://api.san...', 'VT-server-kAuXE...', false) #2 /home/roomnrate/public_html/veritrans/Veritrans/Notification.php(20): Veritrans_Transaction::status(NULL) #3 /home/roomnrate/public_html/veritrans/balik.php(6): Veritrans_Notification->__construct() #4 {main} thrown in /home/roomnrate/public_html/veritrans/Veritrans/ApiRequestor.php on line 96

I use source code example

<?php

require_once('Veritrans.php');
Veritrans_Config::$isProduction = false;
Veritrans_Config::$serverKey = 'VT-server-kAuXESfJyeNPl0go9IpIu92H';
$notif = new Veritrans_Notification();

$transaction = $notif->transaction_status;
$type = $notif->payment_type;
$order_id = $notif->order_id;
$fraud = $notif->fraud_status;

if ($transaction == 'capture') {
  // For credit card transaction, we need to check whether transaction is challenge by FDS or not
  if ($type == 'credit_card'){
    if($fraud == 'challenge'){
      // TODO set payment status in merchant's database to 'Challenge by FDS'
      // TODO merchant should decide whether this transaction is authorized or not in MAP
      echo "Transaction order_id: " . $order_id ." is challenged by FDS";
      } 
      else {
      // TODO set payment status in merchant's database to 'Success'
      echo "Transaction order_id: " . $order_id ." successfully captured using " . $type;
      }
    }
  }
else if ($transaction == 'settlement'){
  // TODO set payment status in merchant's database to 'Settlement'
  echo "Transaction order_id: " . $order_id ." successfully transfered using " . $type;
  } 
  else if($transaction == 'pending'){
  // TODO set payment status in merchant's database to 'Pending'
  echo "Waiting customer to finish transaction order_id: " . $order_id . " using " . $type;
  } 
  else if ($transaction == 'deny') {
  // TODO set payment status in merchant's database to 'Denied'
  echo "Payment using " . $type . " for transaction order_id: " . $order_id . " is denied.";
  }
  else if ($transaction == 'cancel') {
  // TODO set payment status in merchant's database to 'Denied'
  echo "Payment using " . $type . " for transaction order_id: " . $order_id . " is canceled.";
}
?>
What does it mean ?

**Comment by robeth** [comment]
Hi @rachman123, thank you for using this library :smile: 

May i ask what do you want to achieve?

This code intention is to handle _notification hook_
refs:
- http://docs.veritrans.co.id/en/api/methods.html#Validation
- http://docs.veritrans.co.id/en/vtweb/integration_php.html (Step 4)

In short, when there is transaction change, veritrans will notify your server by posting JSON data. The code you posted is utilized to turn JSON data into PHP object.

If you want to do _create transaction_,  you may want to try 
- this [examples](https://github.com/veritrans/veritrans-php/tree/master/examples) (VT-Web is simpler & easier to setup than VT-Direct)
- step by step explained in [VT-Web docs](http://docs.veritrans.co.id/id/vtweb/integration_php.html)

cheers :beers:

**Comment by rachman123** [comment]
Thank you for your response @robeth , is there php extension must be enable to use Veritrans.php?

**Comment by robeth** [comment]
I think the default enabled extension is enough.

Not sure, but I remembered to enable `php curl` extension manually (it was one year ago when using LAMPP).

**Comment by harrypujianto** [comment]
Hi,

The error will displayed, when u open the notification url in the browser and it's normal.
We do notification challenge (get status with notification data). here's the cause of the error Veritrans_Transaction::status(NULL)

The code want to perform a get status, but it need a transaction id, which only exist in the notification. 

so please make sure to separate between notification and finish url. If you want to see the notification data, please log our notification data.
