### ISSUE TITLE
Some Payment Methods Not Shown On VT-Web

### ISSUE THREAD

**Issue by herusdianto** [veritrans/veritrans-php#41]
Hello Sir,

I have a little problem, I want to show all payment methods like in this page http://docs.veritrans.co.id/en/vtweb/integration_php.html but some of payment method doesn't appear on my page, here is the screenshot:
![screenshot-vtweb sandbox veritrans co id 2015-11-14 22-08-53](https://cloud.githubusercontent.com/assets/8720866/11164249/6df75ac4-8b1d-11e5-8a61-0ec85affddc3.png)

Here is my code:
```php
$transaction = [
    'payment_type'        => 'vtweb',
    'vtweb'               => [
        //'enabled_payments'      => ['credit_card'],
        'credit_card_3d_secure' => true,
        //Set Redirection URL Manually
        'finish_redirect_url'   => route('thanks'),
        'unfinish_redirect_url' => route('thanks'),
        'error_redirect_url'    => route('thanks')
    ],
    'transaction_details' => $transaction_details,
    'customer_details'    => $customer_details,
    'item_details'        => $items_details,
];

$vtweb_url = Veritrans_VtWeb::getRedirectionUrl($transaction);
```

**Comment by robeth** [comment]
Hi @herusdianto,

I think the remaining payment methods are not activated for your sandbox account. Please send email request to support@veritrans.co.id to enable these.

Hope it helps :smile:

**Comment by herusdianto** [comment]
Alright Sir, I'll check later.

Thank you.
