### ISSUE TITLE
CDN version of veritrans js

### ISSUE THREAD

**Issue by waskito** [veritrans/veritrans-php#46]
Is there any cdn version of this:
`https://api.sandbox.veritrans.co.id/v2/assets/js/veritrans.js` ?

sometimes it's too slow, and sometimes is not loaded at all

**Comment by Paxa** [comment]
Thank you for feedback, we are having some network maintenance today for our sandbox service.

For now you may use `https://api.veritrans.co.id/v2/assets/js/veritrans.js` - those files are same

**Comment by waskito** [comment]
Thanks @Paxa , If it's not dynamically changed on every request then I prefer to download it then access it locally or push it to our cdn. Is it okay?

**Comment by Paxa** [comment]
From time to time we make some changes in that file, some new features and improvements.
If you wanna keep your own copy then you should make sure it's up to date.

I guess if you use cloudflare or keycdn (which pull files from other places automatically), and you make expiry time for few day then it will be fine
