### ISSUE TITLE
Veritrans Error (400): Validation Error When Using 3DS and Saved CC

### ISSUE THREAD

**Issue by praditau** [veritrans/veritrans-php#53]
When I use 3DS **and** "Save Credit Card" with 3D Secure credit card number listed on this repo I get Veritrans Error (400): Validation Error after I entered "one-time token" 112233

I want to simulate "one-click" in VT-Direct. According to Veritrans Documentation (http://docs.veritrans.co.id/en/vtdirect/other_features.html)

> **1. Initial Transaction** 
> ◦Customer fill the credit card number, CVV, expiry date
> ◦Customer perform 3D Secure authentication
> ◦Merchant receives token
> ◦Merchant uses token to charge transaction
> ◦When transaction successful, merchant saves customer’s token in the database. We name this token as saved_token.
> 
> **2 .Following Transaction** 
> ◦Merchant retrieve customer saved_token from database 
> ◦Merchant uses saved_token to charge transaction

Step to replicate this issue
1. Clone this repo
2. Upload to web server
3. go to URL http://{{YOUR_URL}}/veritrans-php-master/examples/vt-direct/checkout.php
4. Enter **4811 1111 1111 1114** or **5211 1111 1111 1117** (3D Secure) in Card Number field
5. Check/choose 3D Secure and Save Credit Card
6. Click submit payment
7. 3D Secure dialog pops up
8. Enter **112233**
9. Click **OK**
10. I get **Veritrans Error (400): Validation Error**

**Comment by sathishramesh1989** [comment]
Hi,

How you fixed this issue?

**Comment by yocki-s** [comment]
Hi @sathishramesh1989 
 
Error 400 happen because of several thing (Validation Error, merchant sent bad request data example; validation error, invalid transaction type, invalid credit card format, etc.)

https://api-docs.midtrans.com/#code-4xx

**Comment by sathishramesh1989** [comment]
How can we check this
