### ISSUE TITLE
Please bump the version

### ISSUE THREAD

**Issue by imam** [veritrans/veritrans-php#71]
I don't really see the point of not bumping the `1.0.1` version and make people use your `dev-master` instead of bumping the version.

I want to make a Laravel port for your package, but to do that, I have to make sure that people will install your package first and then install mine:
```
composer require veritrans/veritrans-php:dev-master
composer require imam/midtrans-laravel:dev-master
```

Rather than:
```
composer require imam/midtrans-laravel:dev-master
```

Because well, `dev-master` isn't considered stable. Most Laravel user use `stable` package on their production. If I use your `stable` version, it's been 2years since the last bumping :( .

It's not how composer work, I shouldn't tell anyone to install your library first. There is a reason why `composer.json` exist.

Further more, it's not how semantic versioning work. I have to watch your repo for an update so I can update your package in my application, because you don't use the versioning system correctly. 

Isn't it better that whenever you have a patch, like from `1.1` to `1.2`, I'll just do `composer update` and the work is done for me, so I don't have to update the version myself?

You know I really want to use Midtrans for my application, because I want to waste some time to build a Laravel port for your package and make it public for others to use. But this:

![image](https://user-images.githubusercontent.com/8213031/31054737-b9200c74-a6e3-11e7-8d71-d78df8609550.png)

Is something that you guys should consider fixing. Bump your version, and keep bumping whenever new update is exist, so I can just do `composer update` without having to watch your repo every single day. Because that is one of the main reason Composer exist.

Before that, well I'll wait, or should I make my own REST API port instead, I have time before I really need a payment gateway for Imam.tech 🚶 .

Peace, I'll open my door if you have some confusion about how to implement this issue to your package,
 here or email me, we need you to make Indonesia a better country 😄

**Comment by ibnuh** [comment]
+1

**Comment by rizdaprasetya** [comment]
Hi guys,

Sorry for the long delay, this repo version wasn't properly updated. Now we have update the version and create new release. But haven't yet reflect to the Packagist/Composer version. We'll contact our team member that have the access to update the version on Packagist

Same issue:
https://github.com/veritrans/veritrans-php/issues/81

**Comment by rizdaprasetya** [comment]
Please use the updated and composer compatible library: [Midtrans PHP](https://github.com/Midtrans/midtrans-php). For better more modern composer compatibility. Thanks
