### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'CURL Error: Failed to connect to app.sandbox.veritrans.co.id port 443: Connection refused' 

### ISSUE THREAD

**Issue by josenjo** [veritrans/veritrans-php#77]
Fatal error: Uncaught exception 'Exception' with message 'CURL Error: Failed to connect to app.sandbox.veritrans.co.id port 443: Connection refused' in C:\xampp1\htdocs\veritrans\Veritrans\SnapApiRequestor.php:91 Stack trace: #0 C:\xampp1\htdocs\veritrans\Veritrans\SnapApiRequestor.php(28): Veritrans_SnapApiRequestor::remoteCall('https://app.san...', 'SB-Mid-server-3...', Array, true) #1 C:\xampp1\htdocs\veritrans\Veritrans\Snap.php(53): Veritrans_SnapApiRequestor::post('https://app.san...', 'SB-Mid-server-3...', Array) #2 C:\xampp1\htdocs\veritrans\examples\snap\checkout-process.php(84): Veritrans_Snap::getSnapToken(Array) #3 {main} thrown in C:\xampp1\htdocs\veritrans\Veritrans\SnapApiRequestor.php on line 91

**Comment by rizdaprasetya** [comment]
Hi @josenjo our sandbox server no longer accept outdatet TLS connection. Please update your server TLS / OpenSSL version to v1.2 or newer.
