### ISSUE TITLE
PSR-0?

### ISSUE THREAD

**Issue by anz507** [veritrans/veritrans-php#79]
Will there be any updates to make the library PSR-0 ready?

**Comment by carolus10benny** [comment]
Hi @xakzona ,
Thanks for notifying.
We'll reach out to our team member that have access to the PSR-0

**Comment by rizdaprasetya** [comment]
Please use the updated and composer compatible library: [Midtrans PHP](https://github.com/Midtrans/midtrans-php). For better more modern composer compatibility. Thanks
