### ISSUE TITLE
Error Forbidden 403 After changes the Server Key

### ISSUE THREAD

**Issue by mrsnax** [veritrans/veritrans-php#8]
Found Bugs when changes the server key

http://pastebin.com/v5eWBGpq

**Comment by rafeequl** [comment]
Hi @mrsnax can you please elaborate the bugs ? 403 means that you're using the wrong client key. Thanks!

**Comment by Paxa** [comment]
Error Forbidden 403 means your server key is not correct

Please make sure that you use server key for production when `Veritrans_Config::$isProduction = true;` and server key for sandbox when `Veritrans_Config::$isProduction = false;`

@mrsnax problem still appear?

**Comment by mrsnax** [comment]
No, it's clear thanks

On Thursday, April 16, 2015, Pavel <notifications@github.com> wrote:

> Error Forbidden 403 means your server key is not correct
>
> Please make sure that you use server key for production when Veritrans_Config::$isProduction
> = true; and server key for sandbox when Veritrans_Config::$isProduction =
> false;
>
> @mrsnax <https://github.com/mrsnax> problem still appear?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/veritrans/veritrans-php/issues/8#issuecomment-93743205>
> .
>


-- 
Sent from Gmail iPhone


Regards,


Sterli Snax
IT Manager @RajaGPS.co.id
