### ISSUE TITLE
snapToken response null

### ISSUE THREAD

**Issue by dannyerry** [veritrans/veritrans-php#87]
ketika pada di server dev semuanya baik-baik saja (dicoba dengan server key dan client eky mode prod), tetapi ketika berada di server prod ada masalah yaitu balikan snapToken menjadi null. Apakah ini disebebkan oleh cross domain ?.
karena domain dev peminta snap token berbentuk ss.com/tt dan pengirim snapToken untuk transaki adalah ss.com/rr sedangkan untuk server prod peminta snap token xx.yy.com sedangkan pengirim snapToken untuk melakukan transaksi adalah zz.yy.com

**Comment by rizdaprasetya** [comment]
Hi @dannyerry silahkan berikan error message atau screenshot error lengkapnya.

Cross Domain request akan di block oleh browser jika dilakukan pada Frontend Javascript (AJAX) dan dikirim ke url subdomain berbeda. Pada example yg diberikan direpo ini tidak menggunakan AJAX, tetapi langsung backend to backend. Jika follow example, tidak akan terkena proble Cross Domain request blocked.

Thanks

**Comment by dannyerry** [comment]
ini adalah respon yang didapat ketika meminta token snap seperti contoh pada repo ini
![image](https://user-images.githubusercontent.com/25766689/43250389-74328ddc-90e7-11e8-954b-9c9450ab70cc.png)

ini adalah error karena balikan token null
![image](https://user-images.githubusercontent.com/25766689/43250214-0a7b3aa6-90e7-11e8-8c8b-304d83226509.png)
terimakasih

**Comment by dannyerry** [comment]
![image](https://user-images.githubusercontent.com/25766689/43250508-b4c7e6ee-90e7-11e8-8e94-ab093f158b9f.png)
berikut script saya yang saya gunakan untuk mengirim snap token

**Comment by rizdaprasetya** [comment]
> Pada example yg diberikan direpo ini tidak menggunakan AJAX, tetapi langsung backend to backend
Yg saya maksud adalah cara request API snapnya (retrieve token snap), yaitu langsung dari backend, kalo saya liat dari screenshot code di atas, mas menggunakan JS buat trigger request ke API snap melalui method:
`sendSupportToMidtrans`
Nah itu kan javascript yg (tebakan saya) melakukan AJAX ke server, pastikan servernya support CORS.

Kalau tidak mau repot ngurusin CORS, silahkan lakukan request snap token via Backend kemudian di pass ke Frontend JS.

Kalau cara buka snapnya sudah benar, yaitu pakai `snap.pay` sesuai example

Coba lihat di `console` javascript browser ketika function `sendSupportToMidtrans`, cek apakah ada error sejenis seperti ini

![screen shot 2018-07-26 at 3 28 44 pm](https://user-images.githubusercontent.com/13027142/43251162-6ae90538-90e9-11e8-81f5-a092a4462d6b.png)

Berarti itu karena issue CORS

**Comment by dannyerry** [comment]
tidak ada error lain pada function tersebut kecuali error karena snapToken benilai null

**Comment by rizdaprasetya** [comment]
Ini errornya terjadi pada `sendSupportToMidtrans` dimana saya tidak tahu apa yg terjadi disana sehingga var `response.data` anda isinya `null`, silahkan di debug.
Mohon maaf kami tidak bisa bantu kalau tidak ada error message yg jelas yg berasal dari API Midtrans.

**Comment by rizdaprasetya** [comment]
Silahkan cek log backend yg call Library PHP midtrans atau call API Midtrans juga. Jika ada error message silahkan share.

**Comment by dannyerry** [comment]
ternyata karena ada config prod yang salah yang membuat client key pada server prod tidak terdeksi mas....
termikasih atas bantuannya.
mungkin catatan jg untuk example pada repo ini untuk menghandle error ketika ada beberapa variable mandatory yang tidak terisi agar bisa dikeluarkan pesan errprnya karena pada kasus seperti saya balikannya menjadi null sehingga saya harus melakukan dump pada function yang terindikasi

**Comment by rizdaprasetya** [comment]
Baik kalau sudah bisa. Terima kasih infonya.

Jika memang karena ada salah set key, seharusnya akan ter-log di PHP error log atau ada exception thrown. Karena API midtrans akan return validation error message.
Dari library PHP midtrans akan by default throw exception jika API return validation error
https://github.com/veritrans/veritrans-php/blob/e187810f30b8ae4c2e5404d22a90b54c7269b1d0/Veritrans/SnapApiRequestor.php#L98
