### ISSUE TITLE
How to use one-click/recurring feature?

### ISSUE THREAD

**Issue by buddyrocked** [veritrans/veritrans-php#88]
Please provide guide how to implement one-click feature on vt-direct. Start from get token, what parameters are needed, etc.

I already save token on first payment, but when I use it for next payment, I got validation error 'card_cvv is required'.

Regards,

**Comment by rizdaprasetya** [comment]
As the [readme.md](https://github.com/veritrans/veritrans-php#22c-core-api-vt-direct) explained,
Please follow the sample implementation 
https://github.com/veritrans/veritrans-php/blob/master/examples/core-api/checkout.php

Specifically refer to this part for sample get-token parameter:
https://github.com/veritrans/veritrans-php/blob/master/examples/core-api/checkout.php#L90

For using saved_token with [One Click](https://api-docs.midtrans.com/#card-features-one-click) feature, you can directly use `charge`
For using saved_token with [Two Click](https://api-docs.midtrans.com/#card-features-two-click) feature, you need to get-token again before `charge`. Using `card_cvv` & `token_id` as get-token param
