### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by masbenx** [veritrans/veritrans-php#9]
Problem 1
    - The requested package veritrans/veritrans-php could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting

**Comment by rafeequl** [comment]
Hi @masbenx can you please reproduce the error right now ? I think we already fix it. Thanks!
