### ISSUE TITLE
Mengambil banyak transaksi sekaligus,apakah bisa ?

### ISSUE THREAD

**Issue by luthfi-firmansyah** [veritrans/veritrans-php#90]
Hallo,adakah endpoint,atau api methods yg memungkinkan kita mengambil banyak transaksi sekaligus ?

**Comment by rizdaprasetya** [comment]
Hi @luthfi-firmansyah untuk pertanyaan seputar produk/API midtrans silahkan kontak via support[at]midtrans.com untuk response yg lebih cepat.

Tidak ada endpoint untuk bulk get-status, silahkan lakukan request get-status satu per satu. Atau cara paling mudah dan praktis adalah tunggu HTTP notification / web hook. Karena setiap perubahan status transaksi akan dikirimkan

Karena issue tidak relevan dengan repository, akan di close. Silahkan lanjutkan via email support[at]midtrans.com untuk bantuan yg lebih detail.
Thanks.

**Comment by luthfi-firmansyah** [comment]
Terima Kasih @rizdaprasetya
