### ISSUE TITLE
Apakah mendapatkan notifikasi ketika melakukan refund ?

### ISSUE THREAD

**Issue by luthfi-firmansyah** [veritrans/veritrans-php#91]
Misalkan kita melakukan request refund,apakah webhook kita akan mendapatkan notifikasi ?

**Comment by rizdaprasetya** [comment]
Hi @luthfi-firmansyah untuk pertanyaan seputar produk/API midtrans silahkan kontak via support[at]midtrans.com untuk response yg lebih cepat.

Untuk setiap perubahan status transaksi di Midtrans, akan dikirimkan HTTP notification / webhook.

Karena issue tidak relevan dengan repository, akan di close. Silahkan lanjutkan via email support[at]midtrans.com untuk bantuan yg lebih detail.
Thanks.

**Comment by luthfi-firmansyah** [comment]
Terima Kasih @rizdaprasetya
