### ISSUE TITLE
notification always Trying to get property of non-object in ApiRequestor.php line 93

### ISSUE THREAD

**Issue by wahyupermadie** [veritrans/veritrans-php#95]
Hello, i have a problem when received notification handler. I hope anyone can help me, thank you :)

**in my controller**
`$raw_notification = file_get_contents("php://input");`
`$notif = new \Veritrans_Notification()`

**json response**
`{
  "transaction_time": "2019-03-17 01:04:42",
  "transaction_status": "settlement",
  "transaction_id": "69975065-9f30-4b35-b76b-8aa6548889f8",
  "store": "indomaret",
  "status_message": "midtrans payment notification",
  "status_code": "200",
  "signature_key": "a2d8b5139a698fef1f66651e34c1da6380dc36d400b66e04895a9e88d97bfd806de90f32847e8f82c1054954f10dd7ab9e81d5ad17752771786b9d5f86d0e19c",
  "settlement_time": "2019-03-17 01:05:00",
  "payment_type": "cstore",
  "payment_code": "1177855738009350",
  "order_id": "INVOICE20190316000013",
  "gross_amount": "70400.00",
  "approval_code": "73481903060935055266"
}`

**getting error 500
after I check using postman I get an error in ApiRequestor line 93**
`"message": "Trying to get property of non-object",
    "exception": "ErrorException",
    "file": "/home/wahyuper/public_html/goyur/vendor/veritrans/veritrans-php/Veritrans/ApiRequestor.php",
    "line": 93,`

**Comment by rizdaprasetya** [comment]
@wahyupermadie please contact support@midtrans.com for faster response.
The issue can be caused of wrong serverKey & environment configuration while calling `new \Veritrans_Notification()`.
Or the transaction_id received on the notification does not exists, so it throws null object.

`new \Veritrans_Notification()` will query API by transaction_id and using serverKey & Environment used. Wrong value of any of those will cause null object received.
Thanks.
