### ISSUE TITLE
Error Undefined index "email"

### ISSUE THREAD

**Issue by dylorz** [veritrans/veritrans-php#97]
on class method
`Veritrans_Snap::getSnapToken()`

on object "customer_details" when 'email' data is not provided an error with message `Undefined index: email` occurred,

Expected to not have an error, because 'email' is optional

**Comment by rizdaprasetya** [comment]
@dylorz 
This seems like caused this unsafe line of code
https://github.com/veritrans/veritrans-php/blob/382f3514ebb3fb768adc820768c62932d8cfec07/Veritrans/Sanitizer.php#L60

For now the quick workaround would be to set `Veritrans_Config::$isSanitized = false;`

We're currently on progress to rewrite and re-release PHP library that should be much better organized including fixes to open issues here.
For [example we've done so for NodeJS](https://github.com/Midtrans/midtrans-nodejs-client/)

While considering to address the issues on this repo while we have time.
Thanks for reporting, we'll check further.

**Comment by dylorz** [comment]
the workaround solved my problem, thanks.
we will be expecting the library re-release :)
